package com.umain.fortress.security

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import kotlinx.serialization.Serializable
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Symmetric vault backed by the Android Keystore.
 *
 * The AES-256-GCM key never leaves the TEE / StrongBox — `encrypt` and `decrypt` are the only
 * way to do work with it. This is the foundation for at-rest secrecy of tokens, refresh
 * material, and any locally cached credential blobs.
 *
 * Design notes:
 * - StrongBox is requested when available; fall back to TEE-backed silently on devices without.
 * - The key has no user-auth requirement: this is "at rest" protection. Step-up biometrics use
 *   a separate, biometric-gated key (see [BiometricKeyStore]).
 * - GCM IV is 12 bytes, generated by the cipher provider. The IV is stored alongside the
 *   ciphertext in [VaultBlob] — never reuse an IV with the same key.
 */
class KeystoreVault {

    fun encrypt(alias: String, plaintext: ByteArray): VaultBlob {
        val key = getOrCreateKey(alias)
        val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, key) }
        val ciphertext = cipher.doFinal(plaintext)
        return VaultBlob(iv = cipher.iv, ciphertext = ciphertext)
    }

    fun decrypt(alias: String, blob: VaultBlob): ByteArray {
        val key = getOrCreateKey(alias)
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, blob.iv))
        }
        return cipher.doFinal(blob.ciphertext)
    }

    fun invalidate(alias: String) {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        if (ks.containsAlias(alias)) ks.deleteEntry(alias)
    }

    private fun getOrCreateKey(alias: String): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (ks.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        val specBuilder = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            .setRandomizedEncryptionRequired(true)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            specBuilder.setIsStrongBoxBacked(true)
        }

        return try {
            generator.init(specBuilder.build())
            generator.generateKey()
        } catch (e: Exception) {
            // StrongBox not available on this device — retry without it.
            val fallback = KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .setRandomizedEncryptionRequired(true)
                .build()
            generator.init(fallback)
            generator.generateKey()
        }
    }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_TAG_BITS = 128
        private const val KEY_SIZE_BITS = 256

        const val ALIAS_TOKEN_VAULT = "fortress.vault.tokens"
    }
}

@Serializable
data class VaultBlob(
    val iv: ByteArray,
    val ciphertext: ByteArray,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is VaultBlob) return false
        return iv.contentEquals(other.iv) && ciphertext.contentEquals(other.ciphertext)
    }

    override fun hashCode(): Int = 31 * iv.contentHashCode() + ciphertext.contentHashCode()
}
